
name: "Main action file of Docker container actions"
description: "Docker container actions"

inputs:
  GITHUB_TOKEN:
    description: "Token used to access repo"
    required: false
  owner:
    description: owner name
    default: ${{ github.repository_owner }}
    required: false 
  repo:
    description: repository name
    default: ${{ github.repository }}
    required: false 
  base:
    description: Base URI
    default: "https://api.github.com"
    required: false  
  head_ref:  
    description: Head Refer branch
    default: ${{ contains(github.head_ref, 'release') }}
    required: false
  base_ref:
    description: Base Refer branch
    default: ${{ contains(github.base_ref, 'master') }}
    required: false  
  pr_description:
    description: PR description
    required: false  
  pr_number:
    description: PR number
    required: false
  merge_pr:
    description: PR number
    required: false
  close_pr:
    description: PR number
    required: false  
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPO_OWNER: ${{ inputs.owner }}
    REPO_NAME: ${{ inputs.repo }}
    BASE_URI: ${{ inputs.base }}
    HEAD_REF: ${{ inputs.head_ref }}
    BASE_REF: ${{ inputs.base_ref }}
    PR_DESCRIPTION: ${{ inputs.pr_description }}
    PR_NUMBER: ${{ inputs.pr_number }}
    MERGE_PR: ${{ inputs.merge_pr }}
    CLOSE_PR: ${{ inputs.close_pr }}