name: 'Close the PR having DO NOT MERGE LABEL'
on:
  pull_request:
    types: [opened, edited, reopened, labeled]
      
permissions: write-all    
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
 
jobs:
  Do-not-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Close the PR having DO NOT MERGE LABEL
        uses: ./   
