name: check if version from version file already exist as tag
on:
  pull_request:
    types: [opened, edited, reopened]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  file-checker:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checking file existance
        uses: ./

  tag-matcher:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest tag
        id: latestTag
        run: |
          version_file=$(cat VERSION)
          echo "version from version_file -> $version_file"
          echo "version_file=$version_file" >> $GITHUB_OUTPUT
      - name: Match tag with version-file
        uses: ./
        env:
          VERSION_FILE: ${{ steps.latestTag.outputs.version_file }}